### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by xavierfoucrier**
Working on tests.

### CODE REVIEW

**Comment by Sandstedt** [comment]
Could probably remove `'spec/shapes/*.js'` on row 85 in karma.config.js. But I can't try it locally currently to see if it works.

Else I approve. Great work!

**Comment by Sandstedt** [comment]
Maybe should change the npm test script to:

`"test": "pretest && karma start",` to ensure the user/server (like travis) has the latest UMD build before running the test?

**Comment by xavierfoucrier** [comment]
@Sandstedt, no need to do that, because `pretest` is an NPM automated script that run before `test`, like `posttest` that run after tests. See https://docs.npmjs.com/misc/scripts :wink:

**Comment by Sandstedt** [comment]
You learn something everyday 😁

**Pull request merged**
